### ISSUE TITLE
Send entire EncryptedAssertion (not just EncryptedData) to xmlenc.decrypt

### ISSUE THREAD

**Issue by haoleman** [tngan/samlify#85] opened 2017-06-21 14:58 UTC
Because xml-encryption.decrypt tries to decrypt the "EncryptedKey"  (https://github.com/auth0/node-xml-encryption/blob/master/lib/xmlenc.js#L129) before decrypting "EncryptedData", need to pass the entire "EncryptedAssertion"  to xml-encryption.decrypt, so the "EncryptedKey -> EncryptedMethod" can be found with a signed SamlRespone, with a signed and encrypted Assertion. Per the spec (http://docs.oasis-open.org/security/saml/v2.0/saml-schema-assertion-2.0.xsd), the "EncryptedData" and "EncryptedKey" are separate AND the "EncryptedKey" can be referenced from the "EncryptedData"
... which is happening in the attached assertion.

[saml_assertion_refs_EncryptedKey.xml.txt](https://github.com/tngan/samlify/files/1092071/saml_assertion_refs_EncryptedKey.xml.txt)

**Comment by tngan** [comment] 2017-06-21 16:11
@haoleman This is a good catch. Would you also like to fire another issue to `node-xml-encryption` and link this issue to there ? Their documentation shows that `EncryptedData` is passed in the decrypt function even the code can handle both cases.

**Comment by haoleman** [comment] 2017-06-21 17:37
^ https://github.com/auth0/node-xml-encryption/issues/30

**Comment by tngan** [comment] 2017-06-22 01:20
@haoleman Thank you so much. The decryption part in samlify is now inserting the entire encrypted assertion rather than the data section, this enhancement will be delivered in the next release.

**Comment by haoleman** [comment] 2017-06-22 12:54
@tngan  Thx for fixing. FYI I added a comment to node-xml-encryption issue, that relates to the end-to-end use case I'm trying to solve w/ express-saml2/samlify (and deps). 
https://github.com/auth0/node-xml-encryption/issues/30

**Comment by tngan** [comment] 2017-06-22 17:07
@haoleman Since the issue is fixed in samlify, so I would close this issue. Feel free to reopen if you encounter any problem.

**Closed by tngan** 2017-06-22 17:07 UTC
Labels: discussion, enhancement
