### ISSUE TITLE
TypeError: xml is not a function

### ISSUE THREAD

**Issue by makbaraly** [tngan/samlify#448] opened 2021-09-08 08:39 UTC
Hi,

We are facing a strange behaviour since the last 3 days with the library.
It seems that samlify cannot find the xml dependency

`  ● Test suite failed to run

    TypeError: xml is not a function

      74 |
      75 |     // Configuration
    > 76 |     this.sp = ServiceProvider(spSettings);
         |               ^
      77 |     this.idp = IdentityProvider(idpSettings);
      78 |   }
      79 |

      at new SpMetadata (node_modules/samlify/src/metadata-sp.ts:139:14)
      at default_1 (node_modules/samlify/src/metadata-sp.ts:30:10)
      at ServiceProvider.Entity (node_modules/samlify/src/entity.ts:91:37)
      at new ServiceProvider (node_modules/samlify/src/entity-sp.ts:48:5)
      at default_1 (node_modules/samlify/src/entity-sp.ts:27:10)
`

Here is the package.json extract we are using : 

  "dependencies": {
    "@babel/helper-regex": "^7.10.5",
    "@next/bundle-analyzer": "^11.1.0",
    "@types/node": "^16.7.1",
    "@types/react-csv": "^1.1.2",
    "axios": "^0.21.1",
    "axios-cache-adapter": "^2.7.3",
    "basic-auth": "^2.0.1",
    "body-parser": "^1.19.0",
    "classnames": "^2.3.1",
    "cookie-cutter": "^0.2.0",
    "cookie-parser": "^1.4.5",
    "cors": "^2.8.5",
    "cross-var": "^1.1.0",
    "dotenv": "^10.0.0",
    "dotenv-cli": "^4.0.0",
    "downshift": "^6.1.7",
    "eslint-config-airbnb": "^18.2.1",
    "express": "^4.17.1",
    "express-sse": "^0.5.3",
    "formik": "^2.2.9",
    "helmet": "^4.6.0",
    "jsonwebtoken": "^8.5.1",
    "next": "^11.1.0",
    "next-compose-plugins": "^2.2.1",
    "next-transpile-modules": "^8.0.0",
    "pino-http": "^5.7.0",
    "pino-pretty": "^6.0.0",
    "prop-types": "^15.7.2",
    "query-string": "^7.0.1",
    "react": "^17.0.2",
    "react-csv": "^2.0.3",
    "react-dom": "^17.0.2",
    "react-modal": "^3.14.3",
    "react-table": "^7.7.0",
    "redis": "^3.1.2",
    "samlify": "^2.8.0-rc1",
    "ts-node": "^10.2.1",
    "yup": "^0.32.9"
  },
  "devDependencies": {
    "@babel/core": "^7.15.0",
    "@next/eslint-plugin-next": "^11.1.0",
    "@storybook/addon-essentials": "^6.3.7",
    "@storybook/preset-scss": "^1.0.3",
    "@storybook/react": "^6.3.7",
    "@testing-library/jest-dom": "^5.14.1",
    "@testing-library/react": "^12.0.0",
    "@testing-library/user-event": "^13.2.1",
    "@types/classnames": "^2.3.1",
    "@types/jest": "^27.0.1",
    "@types/jest-axe": "^3.5.2",
    "@types/jsonwebtoken": "^8.5.5",
    "@types/react": "^17.0.19",
    "@types/react-modal": "^3.12.1",
    "@types/react-table": "^7.7.2",
    "@types/yup": "^0.29.13",
    "@typescript-eslint/eslint-plugin": "^4.29.3",
    "@typescript-eslint/parser": "^4.29.3",
    "babel-loader": "^8.2.2",
    "babel-preset-react-app": "^10.0.0",
    "commitizen": "^4.2.4",
    "cross-env": "^7.0.3",
    "css-loader": "^6.2.0",
    "cypress": "^8.3.0",
    "cypress-axe": "^0.13.0",
    "cz-conventional-changelog": "^3.3.0",
    "eslint": "^7.32.0",
    "eslint-config-airbnb-typescript": "^14.0.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-import": "^2.24.2",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-prettier": "^3.4.1",
    "eslint-plugin-react": "^7.24.0",
    "eslint-plugin-react-hooks": "^4.2.0",
    "fork-ts-checker-webpack-plugin": "^6.3.2",
    "husky": "^7.0.2",
    "jest": "^27.0.6",
    "jest-axe": "^5.0.1",
    "jest-css-modules": "^2.1.0",
    "lint-staged": "^11.1.2",
    "nock": "^13.1.3",
    "prettier": "^2.3.2",
    "sass": "^1.38.1",
    "sass-loader": "^12.1.0",
    "start-server-and-test": "^1.13.1",
    "style-loader": "^3.2.1",
    "ts-jest": "^27.0.5",
    "ts-loader": "^9.2.5",
    "typescript": "^4.3.5"
  },
  "resolutions": {
    "node-fetch": "^2.6.1",
    "object-path": "^0.11.5",
    "immer": "^8.0.1",
    "xmldom": "github:xmldom/xmldom#0.7.0",
    "ssri": "^8.0.1",
    "merge": "^2.1.1",
    "**/trim": "^1.0.0",
    "postcss": "^8.2.15",
    "browserslist": "^4.16.5",
    "css-what": "^5.0.1",
    "glob-parent": "^5.1.2",
    "prismjs": "^1.24.1"
  }
`

Does it have possibly to do with an version incompatibility between xmldom and samlify ?

Thanks !

**Comment by makbaraly** [comment] 2021-09-08 08:49
I've just tried with "@xmldom/xmldom": "^0.7.4" and "samlify": "^2.8.1": same issue

**Comment by makbaraly** [comment] 2021-09-08 10:09
It looks like the issue is coming from the lib itself, when I ran the test, I could find the same issue as a result

```
/usr/local/bin/node /usr/local/lib/node_modules/npm/bin/npm-cli.js test --scripts-prepend-node-path=auto

> samlify@2.8.1 pretest
> make pretest

mkdir -p build/test; \
                                        cp -a test/key test/misc build/test;

> samlify@2.8.1 test
> NODE_ENV=test nyc ava


  ✖ No tests found in test/index.ts
  ✖ No tests found in test/flow.ts

  ─

  Uncaught exception in test/index.ts

  test/index.ts(287,18): error TS2554: Expected 3 arguments, but got 1.
  test/index.ts(302,18): error TS2554: Expected 3 arguments, but got 1.



  Uncaught exception in test/flow.ts

  test/flow.ts(10,28): error TS2307: Cannot find module '@authenio/samlify-xsd-schema-validator' or its corresponding type declarations.



  Uncaught exception in test/issues.ts

  test/issues.ts:77

   76:   };                                   
   77:   const idp = identityProvider(idpcfg);
   78:   const sp = serviceProvider(spcfg);   

  TypeError: xml is not a function

  › new IdpMetadata (src/metadata-idp.ts:11:31)
  › default_1 (src/metadata-idp.ts:8:86)
  › IdentityProvider.Entity (src/entity.ts:9:458)
  › new IdentityProvider (src/entity-idp.ts:11:2103)
  › default_1 (src/entity-idp.ts:8:88)
  › test/issues.ts:77:15
  › Object.<anonymous> (test/issues.ts:167:3)
  › Module.m._compile (node_modules/ts-node/src/index.ts:858:23)

```

**Comment by damionvega** [comment] 2021-09-11 19:03
Can confirm after attempting to upgrade from `v2.7.7`. 

I believe the issue is via `tsconfig.json`: `"esModuleInterop": true,` here: https://github.com/tngan/samlify/commit/bc25b7b035b3035a0b3e291db9497276513fe6b1#diff-b55cdbef4907b7045f32cc5360d48d262cca5f94062e353089f189f4460039e0R16

An explanation for this: https://www.typescriptlang.org/tsconfig#esModuleInterop:

> This mis-match causes these two issues:
>
> the ES6 modules spec states that a namespace import (`import * as x`) can only be an object, by having TypeScript treating it the same as `= require("x")` then TypeScript allowed for the import to be treated as a function and be callable. This breaks the spec’s recommendations.

**Comment by tngan** [comment] 2021-09-19 10:33
@subsystem7 @damionvega @makbaraly Please try out v2.8.2, I have patched the fixes and test with one of the lint libraries. #449 should be fixed altogether.

**Closed by tngan** 2021-09-19 10:33 UTC

**Comment by damionvega** [comment] 2021-09-19 16:58
v2.8.2 working as expected. Thank you!
