### ISSUE TITLE
verifyTime accepts drift but it's impossible to set the drift for default validation

### ISSUE THREAD

**Issue by Gummibeer** [tngan/samlify#337] opened 2020-01-23 13:18 UTC
relates to issue #256 & PR #323 

We have the problem that the IDP server has a small time drift compared to our SP server time. This produces validation errors because our SP time doesn't match the IDP timeframe in which we are allowed to login.
Our current fix is super hacky, we add a sleep between the IDP response and it's validation because we hav't found a way to pass the, theoretically, possible `drift` parameter.

The validation error comes from
https://github.com/tngan/samlify/blob/a0ab7caa1e585c5d1d56f138cea04fee9a40db2e/src/flow.ts#L226-L231

That's our current code, including the hotfix:
```js
await sleep(5000);
parseResult = await sp.parseLoginResponse(idp, 'post', {body: {SAMLResponse: samlResponse}})
```

Do you have an idea how to pass in a drift to the default `verifyTime()` validation?

**Comment by tngan** [comment] 2020-01-24 17:28
@Gummibeer Which version of samlify are you using ? Is this example working for your use case? See https://samlify.js.org/#/helpers?id=example

samlify doesn't have the checking right now, we delegate the checking to user side, we will plan to include that in the next release, but meanwhile, you can apply the helper function after  the login response is parsed.

**Comment by eisfeuer** [comment] 2020-01-27 10:25
We (@Gummibeer and I) use Samlify version 2.6.1.

Your example doesn't work for us. The problem is that the `sp.parseLoginResponse()` function already checks the time range. We get an exception before we can validate the time range in the parsed login response.
Is there a way to disable the time range check in the `sp.parseLoginResponse()` function?

**Comment by tngan** [comment] 2020-01-28 17:32
@eisfeuer You are right, I will make a patch to expose the drift setting to the constructor.

**Comment by tngan** [comment] 2020-01-28 19:31
@eisfeuer The commit is released with 2.7.0.

**Closed by tngan** 2020-01-28 19:31 UTC
Labels: bug, discussion

**Comment by tngan** [comment] 2020-01-28 19:34
A new property `clockDrifts` is introduced into the configuration of service provider. I have also added two test cases to cover the usage.

See https://samlify.js.org/#/sp-configuration.

https://github.com/tngan/samlify/blob/a6659a30949110a1e08d5fefd487c808a8b03e0f/test/flow.ts#L679-L721

**Comment by Gummibeer** [comment] 2020-01-28 22:31
Thanks @tngan for this quick fix! :) We will try it tomorrow.
